In [2]:
import numpy as np

In [6]:
##1. How to Creating a 3x3 Identity Matrix with Float Data Type?
matrix=np.array([[[1.2,2.2,3.2],[4.3,5.3,6.3],[7.4,8.4,9.4]]],dtype=float)
matrix
                

array([[[1.2, 2.2, 3.2],
        [4.3, 5.3, 6.3],
        [7.4, 8.4, 9.4]]])

In [21]:
##2. Create a 1D Array with Random Values between 0 and 1. 
random_array=np.random.rand(1)
random_array

array([0.06803456])

In [24]:
##3. Create a 2D Array with Random Integer Values. 
random_int=np.random.randint(0,8,size=6).reshape(2,3)
random_int

array([[5, 4, 3],
       [1, 7, 1]], dtype=int32)

In [26]:
##4. Creating an Array Using a Custom Function. 
def custom_logic(i,j):
    return i+j
array=np.fromfunction(custom_logic,(3,4),dtype=int)
print(array)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [31]:
##5. Reshaping a 1D Array into a 2D Array 
array1D=np.array([2,4,5,7,8,7])
print(array)
array2D=array1D.reshape(2,3)
print(array2D)

[2 4 5 7 8 7]
[[2 4 5]
 [7 8 7]]


In [34]:
##6.How to Creating a 3x3 Array of Ones?
array_ones=np.ones((3,3),dtype=int)
print(array_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
 
## 7. How to get the common items between two pythons 
## NumPy? Input: 
a = np. array ([1,2,3,2,3,4,3,4,5,6]) 
b = np. array ([7,2,10,2,7,4,9,4,9,8]) 
## Expected Output: 
## array ([2, 4]) 
common=np.intersect1d(a,b)
print(common)


[2 4]


In [43]:
 ##8. From array a remove all items present in 
##array b Input: 
a = np. array ([1,2,3,4,5]) 
b = np. array ([5,6,7,8,9])
diff=np.setdiff1d(a,b)
print(diff)

[1 2 3 4]


In [57]:
##9. Limit the number of items printed in python NumPy array a to a maximum of 6 elements. 
np.set_printoptions(threshold=6)
a=np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


In [62]:
##10. Drop all nan values from a 1D NumPy
a=np. array ([1,2,3, np.nan,5,6,7, np.nan])
remove_nan=a[~np.isnan(a)]
print(remove_nan)

[1. 2. 3. 5. 6. 7.]


In [69]:
##11. Question: Create a 1D NumPy array of the first 20 natural numbers and a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20.
a=np.arange(1,21)
b=a.reshape(4,5)
print(a)
print(b)

[ 1  2  3 ... 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [83]:
##12. Question: Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, number of dimensions, and data type. 
##Change its data type to float64 and verify the change. 
a=np.arange(24).reshape(2,3,4)
print(a)
shape=a.shape
size=a.size
dim=a.ndim
data_type=a.dtype
print(shape)
print(size)
print(dim)
print(data_type)
print(a.astype(float))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
24
3
int64
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


In [13]:
##13. Question: Reshape a 1D array of 12 elements into a 3x4 2D array and then flatten it back into a 1D array using ravel (). Verify that 
##the flattened array matches the original. 
D=np.arange(1,13)
print(D)
D2=D.reshape(3,4)
print(D2)
D1=D2.ravel()
print(D1)
print("Match:",np.array_equal(D1,D))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Match: True


In [16]:
##14. Question: Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4, 5, 6]), perform element-wise addition, subtraction, multiplication,
##and division. Explain the behavior when dividing by zero.
a = np. array ([1, 2, 3])
b = np. array ([4, 5, 6])
print("ADD:",a+b)
print("SUB",a-b)
print("MULTI",a*b)
# print("Div",a/0)
##Dividing by zero in NumPy doesn't crash your program — it returns inf, -inf, or nan depending on the values.A runtime warning is shown, but execution continues.


ADD: [5 7 9]
SUB [-3 -3 -3]
MULTI [ 4 10 18]
Div [inf inf inf]


C:\Users\Hinali\AppData\Local\Temp\ipykernel_19140\3357743581.py:8: RuntimeWarning: divide by zero encountered in divide
  print("Div",a/0)


In [28]:
##15. Question: Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform element-wise addition using broadcasting. 
##Explain how broadcasting rules apply in this scenario.
D2=np.arange(3,6).reshape(3,1)
D1=np.arange(2,5)
print(D2+D1)
##it allow Numpy to perform opration on arrays of diffrent shape.here both have same 3 rows and other one have 3 column so he work bordcasting 
##and create new array as 3*3.

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [34]:
##16. Question: Generate a random 2D array of integers between 0 and 10. Use  conditional operators to create a Boolean mask identifying elements 
##greater than 5. Replace all elements greater than 5 with the value 5. 
D2=np.arange(0,12).reshape(3,4)
check=D2>5
print(check)


[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [52]:
##17. Question: Given a 4x4 array of random integers, use indexing and slicing to extract:  
## o The subarray consisting of the first two rows and first two columns 
array=np.random.randint(0,40,size=16).reshape(4,4)
print(array)
print("______________")
print("o The entire second row")
print(array[1])
print("______________")
print("o The last column")
print(array[0:4,3])
print("______________")
print("o The subarray consisting of the first two rows and first two columns")
print(array[0:2,(0,1)])

[[33 27 37  1]
 [38  4 17 21]
 [27 29  0 33]
 [13 32 38  5]]
______________
o The entire second row
[38  4 17 21]
______________
o The last column
[ 1 21 33  5]
______________
o The subarray consisting of the first two rows and first two columns
[[33 27]
 [38  4]]


In [35]:
##18. Question: Describe a practical example where NumPy can be used in EDA, AI, ML, and DL, and implement a NumPy solution 
##for a simple task in each area. 
#  1. EDA (Exploratory Data Analysis)
#  Task: Detect and replace missing values (NaN)
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
import numpy as np

# # # Simulated dataset with some missing values
data = np.array([5, 7, np.nan, 10, np.nan, 4])

# # # Detect NaNs
mask = np.isnan(data)

# # # Replace NaNs with the mean of valid numbers
data[mask] = np.nanmean(data)

print("Cleaned Data:", data)
#  Why this matters: In EDA, cleaning missing values is a critical first step.

Cleaned Data: [ 5.   7.   6.5 10.   6.5  4. ]


In [ ]:
##19.Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the matrix. 


In [11]:
##20.Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array 
##with the original. 
OG=np.random.randint(1,50,size=27)
print("OG",OG)
array_3D=OG.reshape(3,3,3)
print("array_3D",array_3D)
new_OG=array_3D.ravel()
print("new_OG",new_OG)
print("OG==new_OG is",np.array_equal(new_OG,OG))


OG [30 46 19 22  5 23 37 20 21 47 38 42 30 37 47  4  2  5 38 21 16  3 26  5
 26 23 36]
array_3D [[[30 46 19]
  [22  5 23]
  [37 20 21]]

 [[47 38 42]
  [30 37 47]
  [ 4  2  5]]

 [[38 21 16]
  [ 3 26  5]
  [26 23 36]]]
new_OG [30 46 19 22  5 23 37 20 21 47 38 42 30 37 47  4  2  5 38 21 16  3 26  5
 26 23 36]
OG==new_OG is True


In [24]:
##21.Perform matrix multiplication of two 2D arrays using np.dot () and @. Compare the results and performance of both methods using a large dataset.
a=np.random.randint(1,20,size=6).reshape(2,3)
b=np.random.randint(1,19,size=6).reshape(3,2)
print(a)
print(b)
print(np.dot(a,b))
print(a@b)

##Compare
import time
# Larger arrays for better test
a_large = np.random.randint(1, 100, size=(1000, 500))
b_large = np.random.randint(1, 100, size=(500, 1000))

start = time.time()
np.dot(a_large, b_large)
print("np.dot time:", time.time() - start)

start = time.time()
a_large @ b_large
print("@ operator time:", time.time() - start)



[[14  8  6]
 [ 3 16  1]]
[[15 13]
 [ 5  9]
 [ 9  9]]
[[304 308]
 [134 192]]
[[304 308]
 [134 192]]
np.dot time: 0.5927634239196777
@ operator time: 0.6999084949493408


In [16]:
##22. Question: Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4, 1). Perform an element-wise operation using broadcasting 
##and explain the result. Use np. new axis to achieve the same result without broadcasting.
D3=np.random.randint(1,20,size=8).reshape(2,1,4)
D2=np.random.randint(1,20,size=4).reshape(4,1)
print(D3)
print(D2)
print(D3*D2)
print(D3+D2)

[[[ 8 11  9 17]]

 [[ 4 13 11 16]]]
[[ 3]
 [12]
 [ 6]
 [ 1]]
[[[ 24  33  27  51]
  [ 96 132 108 204]
  [ 48  66  54 102]
  [  8  11   9  17]]

 [[ 12  39  33  48]
  [ 48 156 132 192]
  [ 24  78  66  96]
  [  4  13  11  16]]]
[[[11 14 12 20]
  [20 23 21 29]
  [14 17 15 23]
  [ 9 12 10 18]]

 [[ 7 16 14 19]
  [16 25 23 28]
  [10 19 17 22]
  [ 5 14 12 17]]]


In [6]:
##23. Question: Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. 
##Replace these values with their squares and leave the rest unchanged.
D2=np.random.rand(6).reshape(2,3)
print(D2)
mask=D2>0.5
print(mask)
D2[mask]=D2[mask]**2
print(D2)


[[0.91035531 0.60592692 0.64458112]
 [0.16866304 0.24180089 0.33866685]]
[[ True  True  True]
 [False False False]]
[[0.8287468  0.36714743 0.41548482]
 [0.16866304 0.24180089 0.33866685]]


In [21]:
##24. Question: Given a 5x5 array of sequential integers, use slicing to:  
a=np.random.randint(1,9,size=25).reshape(5,5)
print(a)
##o Extract the diagonal elements 
print("diagonal elements =",np.diag(a))
##o Replace the elements of the middle row with zeros
middel_row=a.shape[0]//2
a[middel_row]=0
print("Fill 0\n",a)
##o Flip the array vertically and horizontally
print("OG\n",a)
print("vertically Flip\n",np.flipud(a))
print("horizontally Flip\n",np.fliplr(a))

[[4 1 8 5 3]
 [6 1 2 3 6]
 [6 7 5 8 2]
 [6 2 2 7 8]
 [5 6 3 8 2]]
diagonal elements = [4 1 5 7 2]
Fill 0
 [[4 1 8 5 3]
 [6 1 2 3 6]
 [0 0 0 0 0]
 [6 2 2 7 8]
 [5 6 3 8 2]]
OG
 [[4 1 8 5 3]
 [6 1 2 3 6]
 [0 0 0 0 0]
 [6 2 2 7 8]
 [5 6 3 8 2]]
vertically Flip
 [[5 6 3 8 2]
 [6 2 2 7 8]
 [0 0 0 0 0]
 [6 1 2 3 6]
 [4 1 8 5 3]]
horizontally Flip
 [[3 5 8 1 4]
 [6 3 2 1 6]
 [0 0 0 0 0]
 [8 7 2 2 6]
 [2 8 3 6 5]]


In [31]:
##25.Create a 4D array of shape (2, 3, 4, 5) with random integers.Use advanced slicing to extract a subarray and compute the mean along a specified axis.
a=np.random.randint(1,20,size=120).reshape(2,3,4,5)
print(a)
print("subarray\n=", a[0, :, :, 0:3])
sub= a[0, :, :, :3]
print("mean_result \n=", sub.mean(axis=0))


[[[[15  6 12 14 18]
   [10 11  7 14  3]
   [12 10 19 16 16]
   [ 9 19 12  6 11]]

  [[ 2 19 12 11 17]
   [15 12 15 18  3]
   [ 6 11 13 17 16]
   [ 8  6 11  7 11]]

  [[ 2  7  2 12  2]
   [19  6  9  7  5]
   [ 3 19  4 16 11]
   [ 4 19  7 18 13]]]


 [[[ 7  3  3 14 14]
   [ 2  5  1  7 16]
   [ 7 15  6 10  2]
   [ 1 17  3 13  7]]

  [[12  3  7  4  4]
   [ 3  7 16  9 18]
   [ 8 12 17  8  8]
   [16 10 13  3 19]]

  [[ 5 10  2  3 10]
   [ 2  8 17  9 18]
   [10 17  1  9 10]
   [ 9 17 16 15 14]]]]
subarray
= [[[15  6 12]
  [10 11  7]
  [12 10 19]
  [ 9 19 12]]

 [[ 2 19 12]
  [15 12 15]
  [ 6 11 13]
  [ 8  6 11]]

 [[ 2  7  2]
  [19  6  9]
  [ 3 19  4]
  [ 4 19  7]]]
mean_result 
= [[ 6.33333333 10.66666667  8.66666667]
 [14.66666667  9.66666667 10.33333333]
 [ 7.         13.33333333 12.        ]
 [ 7.         14.66666667 10.        ]]


In [34]:
##26.Given an array of shape (10, 20), reshape it to (20, 10) and (5, 40). Discuss the impact on the array's shape, size, and dimensionality. 
a=np.random.randint(1,50,size=200).reshape(10,20)
print("10X20\n",a)
b=a.reshape(20,10)
print("20X10\n",b)
c=a.reshape(5,40)
print("5X40\n",c)

10X20
 [[11 20 46 10 45 39 36 15 24 46  2 29  2 22 10  7  9 30 12 20]
 [23 35 32 24 40 27 15 17 27 27 30 24  8 15 37 38 33 25  7 12]
 [45  4 43  7 38 11  9 48 23 19 32 22 14 27 40  3 37 11  9 36]
 [27 48  7 13 39 34  7 27 17 30 14 34 48 27  7  8 30 11 37 39]
 [ 4 43 28  3 38  5 18 10 24 33 31 26 26 31 29 31 32 25 34 45]
 [ 7 31 25  9 45 38 27 11  4  4 11  2 29 48 34 34 12  5 13 49]
 [37 37  2  4 14 30 16 29 30 48 12 11 19 23 14 46  8 22 31 28]
 [32 44  9 44 29 27 46 29  5 29  9 26 16 16 21  1 21 42 14 26]
 [ 4 27 45 24 21  5 20 25 32 23 24 26 21 44  4 47 18 49 41 10]
 [29 26  4  6 32 31 42 15 38  6 30 41 44 47 24 32 14  8  1 13]]
20X10
 [[11 20 46 10 45 39 36 15 24 46]
 [ 2 29  2 22 10  7  9 30 12 20]
 [23 35 32 24 40 27 15 17 27 27]
 [30 24  8 15 37 38 33 25  7 12]
 [45  4 43  7 38 11  9 48 23 19]
 [32 22 14 27 40  3 37 11  9 36]
 [27 48  7 13 39 34  7 27 17 30]
 [14 34 48 27  7  8 30 11 37 39]
 [ 4 43 28  3 38  5 18 10 24 33]
 [31 26 26 31 29 31 32 25 34 45]
 [ 7 31 25  9 45 38 27 11

In [36]:
##27.Generate a large 2D array and demonstrate the use of np.reshape () and np.ravel () to manipulate its shape for various linear algebra operations
###Generate a large 2D array:
a = np.arange(100).reshape(10, 10)  # 10×10 matrix

###Use reshape() to change shape (e.g., flatten and reshape for multiplication):
b = a.reshape(20, 5)  # reshape to 20×5

###Use ravel() to flatten into 1D (useful for vector operations):
flat = a.ravel()  # shape becomes (100,). 

In [ ]:
##28. Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and 
##set the lower triangular part to zero. Verify the result. 